version: 2.0

workflows:
  version: 2
  test_build_deploy:
    jobs:
      - build
      - deploy-dev:
          requires:
            - build
          filters:
            branches:
              only: dev
      - deploy-pre:
          requires:
            - build
          filters:
            branches:
              only: master
      - deploy-prod:
          requires:
            - deploy-pre
          filters:
            branches:
              only: master

jobs:
  build:
    docker:
      - image: circleci/node:6
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install
          command: yarn install && yarn install -g codeclimate-test-reporter
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Test
          command: yarn test
      - run:
          name: Coverage
          command: codeclimate-test-reporter < coverage/lcov.info
      - run:
          name: Build
          command: yarn build

  deploy-dev:
    docker:
      - image: circleci/node:6
    steps:
      - run:
          name: DEPLOY DEV
          command: "echo DEPLOY DEV"

  deploy-pre:
    docker:
      - image: circleci/node:6
    steps:
      - run:
          name: DEPLOY PRE
          command: "echo DEPLOY PRE"

  deploy-prod:
    docker:
      - image: circleci/node:6
    steps:
      - run:
          name: DEPLOY PROD
          command: "echo DEPLOY PROD"

#   build:
#     docker:
#       - image: circleci/node:6
#     environment:
#       - NODE_ENV: development
#     steps:
#       - checkout
#       - restore_cache:
#           key: dependency-cache-{{ checksum "package.json" }}
#       - run:
#           name: yarn Install
#           command: yarn install
#
#       - save_cache:
#           key: dependency-cache-{{ checksum "package.json" }}
#           paths:
#             - node_modules
#
#   test:
#     docker:
#       - image: circleci/node:7-browsers
#     steps:
#       - checkout
#       - run:
#           name: Test
#           command: yarn test
#       - store_artifacts:
#           path: coverage
#           prefix: coverage
#
#machine:
#  node:
#    version:
#      8.2.1
#
#  environment:
#    NODE_ENV: development
#    CIRCLE_ARTIFACTS: "coverage"
#
#dependencies:
#  override:
#    - npm install:
#        timeout: 180
#
#test:
#  override:
#    - yarn run test:CI
#  post:
#      - yarn run cover
#
#deployment:
#  production:
#    branch: master
#    commands:
#      - yarn run publish:pro
#  staging:
#    branch: pre
#    commands:
#      - yarn run publish:pre
#  dev:
#    branch: dev
#    commands:
#      - yarn run publish:dev
#
