version: 2.0

workflows:
  version: 2
  test_build_deploy:
    jobs:
      - build
      - deploy-dev:
          requires:
            - build
          filters:
            branches:
              only: dev
      - deploy-pre:
          requires:
            - build
          filters:
            branches:
              only: master
      - hold:
         type: approval
         requires:
           - deploy-pre
      - deploy-prod:
          requires:
            - hold
          filters:
            branches:
              only: master

jobs:
  build:
    environment:
      CC_TEST_REPORTER_ID: c8948572d88557d3a8f8b1e4ce7e84dc2dc8b36f31fd6deb6707ba0c6e1cb02a
    docker:
      - image: circleci/node:6
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Setup dependencies
          command: yarn install
      - run:
          name: Setup Code Climate test-reporter
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Run tests
          command: |
            yarn test
            ./cc-test-reporter after-build < coverage/lcov.info
      - run:
          name: Build
          command: yarn build
      - store_artifacts:
          path: build
          destination: build

  deploy-dev:
    docker:
      - image: buildpack-deps:trusty
    steps:
      - run:
          name: Setup awscli
          command: apt-get install -y awscli
      - run:
          name: DEPLOY DEV
          command: aws s3 sync $CIRCLE_ARTIFACTS/build s3://snt-dev --region us-east-1

  deploy-pre:
    docker:
      - image: buildpack-deps:trusty
    steps:
      - run:
          name: Setup awscli
          command: apt-get install -y awscli
      - run:
          name: DEPLOY PRE
          command: aws s3 sync $CIRCLE_ARTIFACTS/build s3://snt-pre us-east-1

  deploy-prod:
    docker:
      - image: buildpack-deps:trusty
    steps:
      - run:
          name: Setup awscli
          command: apt-get install -y awscli
      - run:
          name: DEPLOY PROD
          command: aws s3 sync $CIRCLE_ARTIFACTS/build s3://snt-prod us-east-1

#   build:
#     docker:
#       - image: circleci/node:6
#     environment:
#       - NODE_ENV: development
#     steps:
#       - checkout
#       - restore_cache:
#           key: dependency-cache-{{ checksum "package.json" }}
#       - run:
#           name: yarn Install
#           command: yarn install
#
#       - save_cache:
#           key: dependency-cache-{{ checksum "package.json" }}
#           paths:
#             - node_modules
#
#   test:
#     docker:
#       - image: circleci/node:7-browsers
#     steps:
#       - checkout
#       - run:
#           name: Test
#           command: yarn test
#       - store_artifacts:
#           path: coverage
#           prefix: coverage
#
#machine:
#  node:
#    version:
#      8.2.1
#
#  environment:
#    NODE_ENV: development
#    CIRCLE_ARTIFACTS: "coverage"
#
#dependencies:
#  override:
#    - npm install:
#        timeout: 180
#
#test:
#  override:
#    - yarn run test:CI
#  post:
#      - yarn run cover
#
#deployment:
#  production:
#    branch: master
#    commands:
#      - yarn run publish:pro
#  staging:
#    branch: pre
#    commands:
#      - yarn run publish:pre
#  dev:
#    branch: dev
#    commands:
#      - yarn run publish:dev
#
